extends:
  - eslint:recommended
env:
  node: true
  es6: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
rules:
  semi: [error, always]
  indent: [error, 2]
  quotes: 
    - error
    - single
    - allowTemplateLiterals: true
  no-console: off
