version: '3'
services:
  main:
    build: packages/server/
    # image: kraftwerk28/sec_lab_main
    environment:
      NODE_ENV: production
    # deploy:
    #   replicas: 2
    # depends_on:
    #   - pg
    #   - redis
    # ports:
    #   - 8080:8080
    env_file: .env
    network_mode: host

  service1:
    build:
      context: packages/service-1
      dockerfile: ../../Dockerfile.common
    # image: kraftwerk28/sec_lab_service1
    env_file: .env
    environment:
      NODE_ENV: production
    network_mode: host
    # ports:
    #   - 8001:8001
  service2:
    build:
      context: packages/service-2
      dockerfile: ../../Dockerfile.common
    # image: kraftwerk28/sec_lab_service2
    env_file: .env
    environment:
      NODE_ENV: production
    network_mode: host
    # ports:
    #   - 8001:8001
  auth:
    build:
      context: packages/auth
      dockerfile: ../../Dockerfile.common
    # image: kraftwerk28/sec_lab_auth
    env_file: .env
    environment:
      NODE_ENV: production
    network_mode: host

  reservation:
    build:
      context: packages/reservation
      dockerfile: ../../Dockerfile.common
    # image: kraftwerk28/sec_lab_reservation
    env_file: .env
    environment:
      NODE_ENV: production
    network_mode: host

  redis:
    image: redis
    network_mode: host
