version: '3'
services:
  main:
    build: packages/server/
    environment:
      NODE_ENV: production
    depends_on:
      - pg
      - redis
    ports:
      - 8080:8080
    env_file: .env
    network_mode: host

  service1:
    build:
      context: packages/service-1
      dockerfile: ../../Dockerfile.common
    env_file: .env
    environment:
      NODE_ENV: production

  service2:
    build:
      context: packages/service-2
      dockerfile: ../../Dockerfile.common
    env_file: .env
    environment:
      NODE_ENV: production

  auth:
    build:
      context: packages/auth
      dockerfile: ../../Dockerfile.common
    env_file: .env
    environment:
      NODE_ENV: production

  reservation:
    build:
      context: packages/reservation
      dockerfile: ../../Dockerfile.common
    env_file: .env
    environment:
      NODE_ENV: production

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: kraftwerk28
      POSTGRES_PASSWORD: 271828

  redis:
    image: redis:alpine
