extends:
  - eslint:recommended
env:
  node: true
  es6: true
parserOptions:
  ecmaVersion: 8
  ecmaFeatures:
    experimentalObjectRestSpread: true
  sourceType: module
rules:
  semi: [error, never]
  indent: [error, 2]
  quotes: [error, single]
  no-console: off
